name: Hello World

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: ls -l
      - uses: actions/checkout@v4
      - run: ls -l
